name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
  
  release:
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        # GitHub secret token
        repo_token: 
        # Git tag (for automatic releases)
        automatic_release_tag: true # optional
        # Should this release be marked as a draft?
        draft: true # optional
        # Should this release be marked as a pre-release?
        prerelease: # optional, default is true
        # Release title (for automatic releases)
        title: test # optional
        # Assets to upload to the release
        files: target/release/fixme_report # optional
