name: Rust

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Get last tag
      continue-on-error: true
      run: echo "::set-env name=last_tag::fixme_report $(git describe --abbrev=0)"
    - name: Get current version
      run: echo "::set-env name=current_version::$(./target/release/fixme_report --version)"
      
    - name: Automatic Releases
      if: env.last_tag != env.current_version
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        # GitHub secret token
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        # Git tag (for automatic releases)
        automatic_release_tag: true # optional
        # Should this release be marked as a draft?
        draft: true # optional
        # Should this release be marked as a pre-release?
        prerelease: false # optional, default is true
        # Release title (for automatic releases)
        title: test # optional
        # Assets to upload to the release
        files: target/release/fixme_report # optional

